### POST send email - NB: Change receiver to your own email
@email = http://localhost:7070/api/email

POST {{email}}/send
Content-Type: application/json

{
  "receiver": "ostekugle@gmail.com",
  "subject": "subject test",
  "message": "Hello person, \n\nThis is new line \n\nWith best regards, \nOskar"
}
