### POST send email - NB: Change receiver to your own email
@email = http://localhost:7070/api/email

POST {{email}}/send
Content-Type: application/json

{
    "receiver": "email@gmail.com",
    "subject": "subject test",
    "message": "message test, \nthis is new line \nmed venlig hilsen \nOskar"
}

