###
### employees = http://localhost:8080/employees
### shifts = http://localhost:8080/shifts


### POST NEW EMPLOYEE

POST {{employees}}/
Content-Type: application/json

{
    "name": "Danny Trelburger"
}

### GET ALL EMPLOYEES

GET {{employees}}/

### GET EMPLOYEE BY ID 1

GET {{employees}}/4

### GET ALL SHIFTS

GET {{shifts}}/

### POST NEW SHIFT

POST {{shifts}}?employee_id=9
Content-Type: application/json

{
    "shiftStart": "2024-05-21T08:00:00",
    "shiftEnd": "2024-05-21T16:00:00"
}

### DELETE SHIFT !!

DELETE {{shifts}}/6/delete

### PUNCH IN SHIFT WITH ID 1

POST {{shifts}}/1/punch-in

### PUNCH OUT SHIFT WITH ID 1

POST {{shifts}}/1/punch-out
