### POST

POST {{url}}/managers/employees
Content-Type: application/json

{
  "employeename": "Peter",
  "role": "rolle"
}

### POST 2

POST {{url}}/example
Content-Type: application/json

{
  "name": "Peter2",
  "description": "min anden beskrivelse"
}

### GET ALL

GET {{url}}/example

### GET BY ID 1

GET {{url}}/example/1

### DELETE ID 1

DELETE {{url}}/example/1

### GET ALL

GET {{url}}/example

### GET BY ID 1

GET {{url}}/example/1