
### POST NEW EMPLOYEE

POST {{employees}}/
Content-Type: application/json

{
  "email": "tony@mail",
  "username": "Shtony Babylonia",
  "password": "admin"
}

### GET ALL EMPLOYEES

GET {{employees}}/

### GET EMPLOYEE BY ID 1

GET {{employees}}/1

### GET ALL SHIFTS

GET {{shifts}}/

### POST NEW SHIFT

POST {{shifts}}?employee_id=1
Content-Type: application/json

{
  "shiftStart": "2021-01-01T08:00:00",
  "shiftEnd": "2021-01-01T16:00:00"
}
