
### GET all shifts

GET {{url}}/shifts

### GET shift by status

GET {{url}}/shifts/FOR_SALE

###

GET {{url}}/shifts/COVERED

### update shift status

PATCH {{url}}/shifts/1/status?s=FOR_SALE

### Fail on not found

PATCH {{url}}/shifts/100/status?s=FOR_SALE

### Create buyRequest

POST {{url}}/shifts/1/request
content-type: application/json

{
    "userId": 1,
    "shiftId": 1
}

### Get buyrequest by shiftId

GET {{url}}/shifts/1/request